version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      npm-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 5
  - package-ecosystem: "npm"
    directory: "/apps/api"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      npm-apps-api-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 5
  - package-ecosystem: "npm"
    directory: "/apps/web"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      npm-apps-web-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 5
  - package-ecosystem: "npm"
    directory: "/packages/schemas"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      npm-packages-schemas-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 5
  - package-ecosystem: "npm"
    directory: "/packages/shared-types"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      npm-packages-shared-types-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 5
  - package-ecosystem: "docker"
    directory: "/apps/api"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      docker-apps-api-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 5
  - package-ecosystem: "docker"
    directory: "/apps/web"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      docker-apps-web-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 5
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      githubactions-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 5