#!/usr/bin/env bun
/**
 * Interactive project installer / renamer.
 *
 * Rebrands this starter kit in-place: every `starterkit` token (npm scope
 * `@starterkit/*`, docker project + container names, OrbStack domains, DB
 * credentials, seed email domain) and every `Starter Kit` display string is
 * swapped for your project's name.
 *
 *   bun run setup                 # interactive
 *   bun run setup --name my-app --display "My App" --yes
 *   bun run setup --dry-run       # preview, write nothing
 *
 * Zero dependencies — runs on a fresh clone before `bun install`.
 */
import { readdirSync, statSync, readFileSync, writeFileSync, renameSync, rmSync } from 'node:fs';
import { join, basename, dirname, relative } from 'node:path';
import { createInterface } from 'node:readline/promises';
import { spawnSync } from 'node:child_process';
import { stdin, stdout, exit } from 'node:process';

// Repo root = parent of this script's dir (scripts/), regardless of cwd.
const ROOT = join(import.meta.dir, '..');
const SELF = import.meta.path;

// ── what gets rebranded ──────────────────────────────────────────────────────
const OLD_SLUG = 'starterkit'; // lowercase brand: scope, env, docker, domains, db
const OLD_DISPLAY = /starter kit/gi; // human-facing name (any casing)

// ── what never gets touched ──────────────────────────────────────────────────
const EXCLUDE_DIRS = new Set([
  'node_modules',
  '.git',
  'dist',
  '.turbo',
  '.vscode',
  '.idea',
  'storage',
  'drizzle', // generated SQL migrations — leave as-is
]);
// Lockfiles are regenerated by `bun install`, not hand-edited.
const EXCLUDE_FILES = new Set(['bun.lock', 'package-lock.json', 'yarn.lock', 'pnpm-lock.yaml']);
// Treat these extensions as binary and skip (belt-and-suspenders with NUL check).
const BINARY_EXT = new Set([
  '.png',
  '.jpg',
  '.jpeg',
  '.gif',
  '.webp',
  '.ico',
  '.svg',
  '.woff',
  '.woff2',
  '.ttf',
  '.eot',
  '.pdf',
  '.lock',
]);

// ── CLI flag parsing ─────────────────────────────────────────────────────────
const args = process.argv.slice(2);
function flag(name: string): string | undefined {
  const i = args.indexOf(`--${name}`);
  if (i === -1) return undefined;
  const next = args[i + 1];
  return next && !next.startsWith('--') ? next : '';
}
const hasFlag = (name: string) => args.includes(`--${name}`);

const DRY_RUN = hasFlag('dry-run');
const ASSUME_YES = hasFlag('yes') || hasFlag('y');

// ── helpers ──────────────────────────────────────────────────────────────────
const C = {
  reset: '\x1b[0m',
  dim: '\x1b[2m',
  bold: '\x1b[1m',
  cyan: '\x1b[36m',
  green: '\x1b[32m',
  yellow: '\x1b[33m',
  red: '\x1b[31m',
};
const slugify = (s: string) =>
  s
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
const isValidSlug = (s: string) => /^[a-z][a-z0-9-]*[a-z0-9]$/.test(s) && !s.includes('--');
const titleize = (slug: string) =>
  slug
    .split('-')
    .filter(Boolean)
    .map((w) => w[0]!.toUpperCase() + w.slice(1))
    .join(' ');

function isBinary(buf: Buffer): boolean {
  const len = Math.min(buf.length, 8000);
  for (let i = 0; i < len; i++) if (buf[i] === 0) return true;
  return false;
}

/** Recursively collect processable files + any paths whose name carries the token. */
function walk(dir: string, files: string[], named: string[]): void {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      if (EXCLUDE_DIRS.has(entry.name)) continue;
      if (entry.name.includes(OLD_SLUG)) named.push(full);
      walk(full, files, named);
    } else if (entry.isFile()) {
      if (full === SELF) continue;
      if (EXCLUDE_FILES.has(entry.name)) continue;
      const ext = entry.name.slice(entry.name.lastIndexOf('.'));
      if (BINARY_EXT.has(ext)) continue;
      if (entry.name.includes(OLD_SLUG)) named.push(full);
      files.push(full);
    }
  }
}

function rebrand(text: string, slug: string, display: string): string {
  return text.replace(OLD_DISPLAY, display).split(OLD_SLUG).join(slug);
}

async function main() {
  console.log(
    `\n${C.bold}${C.cyan}◆ Project installer${C.reset} ${C.dim}— rebrand this starter kit${C.reset}\n`,
  );
  if (DRY_RUN) console.log(`${C.yellow}⚠ dry-run: no files will be written${C.reset}\n`);

  const rl = createInterface({ input: stdin, output: stdout });
  rl.on('SIGINT', () => {
    console.log(`\n${C.red}✗ cancelled${C.reset}`);
    exit(130);
  });

  async function ask(
    q: string,
    def: string,
    validate?: (v: string) => string | null,
  ): Promise<string> {
    if (ASSUME_YES) return def;
    for (;;) {
      const raw = (
        await rl.question(`${C.bold}? ${q}${C.reset} ${C.dim}(${def})${C.reset} `)
      ).trim();
      const val = raw || def;
      const err = validate?.(val);
      if (err) {
        console.log(`  ${C.red}${err}${C.reset}`);
        continue;
      }
      return val;
    }
  }
  async function confirm(q: string, def: boolean): Promise<boolean> {
    if (ASSUME_YES) return def;
    const hint = def ? 'Y/n' : 'y/N';
    const raw = (await rl.question(`${C.bold}? ${q}${C.reset} ${C.dim}(${hint})${C.reset} `))
      .trim()
      .toLowerCase();
    if (!raw) return def;
    return raw === 'y' || raw === 'yes';
  }

  // 1. project slug
  const defaultSlug = slugify(basename(ROOT)) || 'my-app';
  const slug = await ask('Project name (kebab-case)', flag('name') || defaultSlug, (v) =>
    isValidSlug(v) ? null : 'lowercase letters, digits and single hyphens only (e.g. my-app)',
  );
  if (slug === OLD_SLUG) {
    console.log(`${C.yellow}Name is already "${OLD_SLUG}" — nothing to do.${C.reset}`);
    rl.close();
    return;
  }

  // 2. display name
  const display = await ask('Display name', flag('display') || titleize(slug));

  // 3. options
  const doGitReset = await confirm('Reset git history (fresh repo)?', false);
  const doInstall = await confirm('Run `bun install` afterwards?', true);
  const doSelfDestruct = await confirm('Remove this installer when done?', true);

  rl.close();

  // summary
  console.log(`\n${C.bold}About to rebrand:${C.reset}`);
  console.log(`  ${C.dim}npm scope    ${C.reset}@${OLD_SLUG}/*  ${C.dim}→${C.reset}  @${slug}/*`);
  console.log(`  ${C.dim}token        ${C.reset}${OLD_SLUG}  ${C.dim}→${C.reset}  ${slug}`);
  console.log(`  ${C.dim}display      ${C.reset}Starter Kit  ${C.dim}→${C.reset}  ${display}`);
  console.log();

  // ── collect + transform ───────────────────────────────────────────────────
  const files: string[] = [];
  const named: string[] = [];
  walk(ROOT, files, named);

  let changedFiles = 0;
  let totalHits = 0;
  for (const file of files) {
    const buf = readFileSync(file);
    if (isBinary(buf)) continue;
    const text = buf.toString('utf8');
    const out = rebrand(text, slug, display);
    if (out === text) continue;
    // count token hits for the report
    const hits =
      (text.match(new RegExp(OLD_SLUG, 'g')) ?? []).length + (text.match(OLD_DISPLAY) ?? []).length;
    totalHits += hits;
    changedFiles++;
    if (!DRY_RUN) writeFileSync(file, out);
    console.log(`  ${C.green}✓${C.reset} ${relative(ROOT, file)} ${C.dim}(${hits})${C.reset}`);
  }

  // rename any files/dirs whose NAME carries the token (deepest first)
  const renamedPaths = named
    .sort((a, b) => b.length - a.length)
    .map((p) => {
      const next = join(dirname(p), basename(p).split(OLD_SLUG).join(slug));
      if (!DRY_RUN) renameSync(p, next);
      console.log(
        `  ${C.green}⤷${C.reset} ${relative(ROOT, p)} ${C.dim}→${C.reset} ${relative(ROOT, next)}`,
      );
      return next;
    });

  console.log(
    `\n${C.bold}${DRY_RUN ? 'Would change' : 'Changed'}${C.reset} ${changedFiles} files ` +
      `${C.dim}(${totalHits} replacements)${C.reset}` +
      (renamedPaths.length ? `, renamed ${renamedPaths.length} paths` : ''),
  );

  if (DRY_RUN) {
    console.log(`\n${C.yellow}dry-run complete — re-run without --dry-run to apply.${C.reset}`);
    return;
  }

  // ── post steps ─────────────────────────────────────────────────────────────
  if (doGitReset) {
    rmSync(join(ROOT, '.git'), { recursive: true, force: true });
    const r = spawnSync('git', ['init', '-q'], { cwd: ROOT, stdio: 'inherit' });
    if (r.status === 0) console.log(`${C.green}✓${C.reset} git history reset`);
  }

  if (doSelfDestruct) {
    // Strip the installer + its npm scripts, then delete the file (and scripts/ if empty).
    const pkgPath = join(ROOT, 'package.json');
    try {
      const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'));
      if (pkg.scripts) {
        delete pkg.scripts.setup;
        delete pkg.scripts.rename;
        writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + '\n');
      }
    } catch {
      /* leave package.json untouched if it can't be parsed */
    }
    rmSync(SELF, { force: true });
    try {
      if (readdirSync(join(ROOT, 'scripts')).length === 0)
        rmSync(join(ROOT, 'scripts'), { recursive: true });
    } catch {
      /* scripts/ has other files — keep it */
    }
    console.log(`${C.green}✓${C.reset} installer removed`);
  }

  if (doInstall) {
    console.log(`\n${C.dim}Installing dependencies…${C.reset}`);
    spawnSync('bun', ['install'], { cwd: ROOT, stdio: 'inherit' });
  }

  console.log(`\n${C.green}${C.bold}✓ Done.${C.reset} ${display} is ready.\n`);
  console.log(`${C.dim}Next:${C.reset} review .env, then ${C.bold}bun run dev${C.reset}\n`);
}

main().catch((err) => {
  console.error(`\n${C.red}✗ ${err instanceof Error ? err.message : String(err)}${C.reset}`);
  exit(1);
});
